services:
  schniffer:
    build: .
    container_name: schniffer-bot
    env_file:
      - ${SCHNIFFER_ENV:-.env}
    environment:
      - PROD=true
      - DB_PATH=/app/data/schniffer.sqlite
    volumes:
      - ${SCHNIFFER_DATA:-./data}:/app/data
    restart: unless-stopped
    ports:
      - "8069:8069"
    networks:
      - default
      - home_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  home_default:
    external: true
