package main

import (
	"fmt"

	"github.com/brensch/schniffer/internal/providers"
)

func main() {
	rc := providers.NewReserveCalifornia()

	// Test the composite ID format that would be generated by the provider
	testCases := []string{
		"1260/2181", // This is what the provider would now generate internally
		"123/456",
		"invalid-format",
		"",
	}

	for _, campgroundID := range testCases {
		url := rc.CampsiteURL(campgroundID, "")
		fmt.Printf("Campground ID: %s -> URL: %s\n", campgroundID, url)
	}
}
